# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db1437ddd63775c3829fec4ce6922f95148f9234aedf54de6c9dc2ef61dd47b24a86eda0453855580d075162eaf6e58974d6b9c4cc0b9d66ebfd163c2d13a78f

test:
  secret_key_base: 98b9c411c2e653836b54dffcbd5df9dbddebaef8b7e2b547ff599babd3364f49595ea4ac9c2ccbb863a8bafa66cd05c93bb455ae0fcb4436665af52a26812761

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
